### ISSUE TITLE
Warning/Error on Status Page: Network incomplete frames hit 250

### ISSUE THREAD

**Issue by nmbgeek** [Pixelcontroller/f16v4_issues#37]
When receiving data from xLights or FPP I receive this message on the status page almost instantly when I play any sequence:

Network incomplete frames hit 250. Network or configuration issue is likely.

All devices are wired ethernet.  Posted issue on forums and another user commented they also had this warning and had to downgrade to build 20 to resolve.

**Comment by keithsw1111** [comment]
This almost is always due to you having two sources sending data to the controller.

Sent from my iPhone

On 27 Nov 2022, at 8:13 am, Clint Johnson ***@***.***> wrote:

﻿

When receiving data from xLights or FPP I receive this message on the status page almost instantly when I play any sequence:

Network incomplete frames hit 250. Network or configuration issue is likely.

All devices are wired ethernet. Posted issue on forums and another user commented they also had this warning and had to downgrade to build 20 to resolve.

**Comment by nmbgeek** [comment]
If I stop FPP no other device is sending data per the Falcon interface and xLights is completely shutdown.

**Comment by JonD24** [comment]
Confirming several users complaining of issue on Falcon Forum.  Can confirm same issue personally.  Firmware 21 error was constant, downgraded to firmware 20, which seemed a little better, but that could just be illusion.   In my case it was F16v4 fw 21 and fw 22.  Forum users are complaining of issue with new F48NS model running ver 23 as well.

**Comment by dpitts** [comment]
HI

Build 22 is an issue. Builds other than Build 23 is not supported on F48V4. What issue are you having with Build 23?

Thank you,

David Pitts
***@***.***

**Comment by keithsw1111** [comment]
This happens for one of two reasons:

1. You defined on the controller that it should expect certain universes ... then you dont send the controller those universes.
2. You send the universes but you send them out of order (this is not a critical problem but not ideal from a processing perspective).

**Comment by JonD24** [comment]
Sorry 22 was typo.  Was using 20 and 21, NOT 22.  F48NS users are basically just commenting on older forum entries that they have this same issue.  They are not going into details.  

In my case I have no issues with v3 products ever.  This only impacts my F16v4 devices.  I do assign each port on the controller a universe in numeric order regardless if it is used.  Example on controller 192.168.1.100 the first port would be universe 101, the second port would be universe 102.  I do tell it to receive and assign it to a port, so for every ying there is a yang.  

I pulled my v4 out of storage and plugged in next to the FPP.  I started a show and immediately got the error.  I looked through the configuration and did notice that the serial output settings was set to universe that did not exist on the controller.  It was displayed in error RED.  I do not use the serial DMX feature, but set it to a valid universe and the error quit displaying almost immediately.  I will keep an eye on it and post back if I have any further issues.  Thanks!

**Comment by keithsw1111** [comment]
So could it be that you are not sending the universes sequentially ... (parallel send?) That would trip this warning.

**Comment by JonD24** [comment]
Follow up.  I posted my fix on the forum and it appears to have resolved most issues for others as well.  I think my issue was that I changed the IP of the v4 controllers last season.  I suspect that when I originally set them out, I had assigned a universe to the serial port.  Since I was not using the DMS serial port, when I changed the IP address, I did not notice it at the old universe and it did not get updated.

Not only did it resolve the network error, it made the controller respond much better.  I was noticing glitches when playing the show last year.  This was only impacting the v4 controllers.  Nothing that made the show unwatchable, but on fast sequences you could tell it was having a hard time keeping up.  As soon as I corrected the universe number on the serial port, it was like the controller had drank an energy drink.  The web page response was noticeably much faster.  Others having the same issue said the same thing.  I see you removed the warning in V24, but I think I am glad the error was there.  Fixing the universe issue has resolved other issues for me.

**Comment by keithsw1111** [comment]
Build 25 will not display this warning ... unless you turn it on using advanced options.
